image: golang:1.12

variables:
  GOPATH: /gopath
  GO_PROJECT_DIR: ${GOPATH}/src/gitlab.com/sandykarunia/fudge

before_script:
  - echo "GO_PROJECT_DIR=${GO_PROJECT_DIR}"
  - chmod +x ${CI_PROJECT_DIR}/scripts/*
  - mkdir -p ${GO_PROJECT_DIR}
  - cp -r ${CI_PROJECT_DIR}/. ${GO_PROJECT_DIR}
  - cd ${GO_PROJECT_DIR}
  - go get -t -v -d ./...
  - go get -u golang.org/x/lint/golint

stages:
  - test
  - build
  
test:
  stage: test
  script:
    - ./scripts/test.sh
    
build:
  stage: build
  script:
    - ./scripts/build.sh
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    paths:
    - ${CI_PROJECT_DIR}/dist/
  variables:
    BUILD_DIST_FOLDER: ${CI_PROJECT_DIR}/dist/
  only:
    - master
