// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Path is an autogenerated mock type for the Path type
type Path struct {
	mock.Mock
}

// BoxDir provides a mock function with given fields:
func (_m *Path) BoxDir() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// FudgeDir provides a mock function with given fields:
func (_m *Path) FudgeDir() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsolateBinary provides a mock function with given fields:
func (_m *Path) IsolateBinary() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
