// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import time "time"

// Signature is an autogenerated mock type for the Signature type
type Signature struct {
	mock.Mock
}

// IsValidHMACSignature provides a mock function with given fields: signature, now, timestamp, nonce, secret, payload
func (_m *Signature) IsValidHMACSignature(signature string, now time.Time, timestamp time.Time, nonce string, secret string, payload *string) bool {
	ret := _m.Called(signature, now, timestamp, nonce, secret, payload)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time, string, string, *string) bool); ok {
		r0 = rf(signature, now, timestamp, nonce, secret, payload)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
