// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// String is an autogenerated mock type for the String type
type String struct {
	mock.Mock
}

// GenerateRandomAlphanumeric provides a mock function with given fields: length
func (_m *String) GenerateRandomAlphanumeric(length int) string {
	ret := _m.Called(length)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(length)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
