// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Sniffers is an autogenerated mock type for the Sniffers type
type Sniffers struct {
	mock.Mock
}

// SniffControlGroupSupport provides a mock function with given fields:
func (_m *Sniffers) SniffControlGroupSupport() {
	_m.Called()
}

// SniffLanguageCppSupport provides a mock function with given fields:
func (_m *Sniffers) SniffLanguageCppSupport() {
	_m.Called()
}

// SniffLanguagePython3Support provides a mock function with given fields:
func (_m *Sniffers) SniffLanguagePython3Support() {
	_m.Called()
}
