version: 2.1

jobs:
  install:
    docker:
      - image: golang:1.12
    steps:
      - checkout
      - run: echo 'export GOPATH="/gopath"' >> $BASH_ENV
      - run: echo 'export GO_PROJECT_DIR="${GOPATH}/src/github.com/sandykarunia/fudge"' >> $BASH_ENV
      - run: echo "GO_PROJECT_DIR=${GO_PROJECT_DIR}"
  test:
    docker:
      - image: golang:1.12
    steps:
      - run: echo "${GO_PROJECT_DIR}"
  build:
    docker:
      - image: golang:1.12
    steps:
      - run: echo "${GO_PROJECT_DIR}"


workflows:
  default_wf:
    jobs:
      - install
      - test:
          requires:
            - install

