version: 2.1

commands:
  set_env:
    description: "Set necessary environment variables for all jobs"
    steps:
      - run: export GOPATH="/gopath"
      - run: export GO_PROJECT_DIR="${GOPATH}/src/github.com/sandykarunia/fudge"
      - run: echo "GO_PROJECT_DIR=${GO_PROJECT_DIR}"

jobs:
  build:
    docker:
      - image: golang:1.12
    steps:
      - checkout
      - set_env

