// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"gitlab.com/sandykarunia/fudge/groundcheck"
	"gitlab.com/sandykarunia/fudge/sdk"
	"gitlab.com/sandykarunia/fudge/utils"
)

// Injectors from server_wire.go:

func Instance() Server {
	osFunctions := sdk.ProvideOSFunctions()
	system := utils.ProvideSystem(osFunctions)
	groundCheck := groundcheck.Provider(system)
	server := Provider(groundCheck)
	return server
}
