// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"gitlab.com/sandykarunia/fudge/groundcheck"
	"gitlab.com/sandykarunia/fudge/groundcheck/checkers"
	"gitlab.com/sandykarunia/fudge/sdk"
	"gitlab.com/sandykarunia/fudge/utils"
)

// Injectors from server_wire.go:

func Instance() Server {
	osFunctions := sdk.ProvideOSFunctions()
	execFunctions := sdk.ProvideExecFunctions()
	system := utils.ProvideSystem(osFunctions, execFunctions)
	ioFunctions := sdk.ProvideIOFunctions()
	file := utils.ProvideFile(ioFunctions, osFunctions)
	path := utils.ProvidePath(system)
	checkersCheckers := checkers.Provider(system, file, path)
	groundCheck := groundcheck.Provider(checkersCheckers)
	server := Provider(groundCheck)
	return server
}
