// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"github.com/sandykarunia/fudge/grader"
	"github.com/sandykarunia/fudge/groundcheck"
	"github.com/sandykarunia/fudge/groundcheck/checkers"
	"github.com/sandykarunia/fudge/logger"
	"github.com/sandykarunia/fudge/sandbox"
	"github.com/sandykarunia/fudge/sdk"
	"github.com/sandykarunia/fudge/server/handler"
	"github.com/sandykarunia/fudge/utils"
)

// Injectors from server_wire.go:

func Instance() Server {
	osFunctions := sdk.ProvideOSFunctions()
	execFunctions := sdk.ProvideExecFunctions()
	system := utils.ProvideSystem(osFunctions, execFunctions)
	ioFunctions := sdk.ProvideIOFunctions()
	file := utils.ProvideFile(ioFunctions, osFunctions)
	path := utils.ProvidePath(system, osFunctions)
	checkersCheckers := checkers.Provider(system, file, path)
	groundCheck := groundcheck.Provider(checkersCheckers)
	loggerLogger := logger.Provider(osFunctions, path)
	factory := sandbox.Provider(osFunctions, ioFunctions, path, system, loggerLogger)
	graderGrader := grader.Provider(factory, loggerLogger)
	handlerHandler := handler.Provider(graderGrader, loggerLogger)
	server := Provider(groundCheck, handlerHandler, loggerLogger)
	return server
}
