// Code generated by mockery v1.0.0
package mocks

import (
	exec "os/exec"

	mock "github.com/stretchr/testify/mock"
)

// ExecFunctions is an autogenerated mock type for the ExecFunctions type
type ExecFunctions struct {
	mock.Mock
}

// Command provides a mock function with given fields: name, arg
func (_m *ExecFunctions) Command(name string, arg ...string) *exec.Cmd {
	_va := make([]interface{}, len(arg))
	for _i := range arg {
		_va[_i] = arg[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *exec.Cmd
	if rf, ok := ret.Get(0).(func(string, ...string) *exec.Cmd); ok {
		r0 = rf(name, arg...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exec.Cmd)
		}
	}

	return r0
}
