// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// FlagFunctions is an autogenerated mock type for the FlagFunctions type
type FlagFunctions struct {
	mock.Mock
}

// Bool provides a mock function with given fields: name, value, usage
func (_m *FlagFunctions) Bool(name string, value bool, usage string) *bool {
	ret := _m.Called(name, value, usage)

	var r0 *bool
	if rf, ok := ret.Get(0).(func(string, bool, string) *bool); ok {
		r0 = rf(name, value, usage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bool)
		}
	}

	return r0
}

// Parse provides a mock function with given fields:
func (_m *FlagFunctions) Parse() {
	_m.Called()
}
