// Code generated by mockery v1.0.0
package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// FmtFunctions is an autogenerated mock type for the FmtFunctions type
type FmtFunctions struct {
	mock.Mock
}

// Fprintf provides a mock function with given fields: w, format, a
func (_m *FmtFunctions) Fprintf(w io.Writer, format string, a ...interface{}) (int, error) {
	var _ca []interface{}
	_ca = append(_ca, w, format)
	_ca = append(_ca, a...)
	ret := _m.Called(_ca...)

	var r0 int
	if rf, ok := ret.Get(0).(func(io.Writer, string, ...interface{}) int); ok {
		r0 = rf(w, format, a...)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(io.Writer, string, ...interface{}) error); ok {
		r1 = rf(w, format, a...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
