// Code generated by mockery v1.0.0
package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// IOFunctions is an autogenerated mock type for the IOFunctions type
type IOFunctions struct {
	mock.Mock
}

// Copy provides a mock function with given fields: dest, src
func (_m *IOFunctions) Copy(dest io.Writer, src io.Reader) (int64, error) {
	ret := _m.Called(dest, src)

	var r0 int64
	if rf, ok := ret.Get(0).(func(io.Writer, io.Reader) int64); ok {
		r0 = rf(dest, src)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(io.Writer, io.Reader) error); ok {
		r1 = rf(dest, src)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
