// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package utils

import (
	"gitlab.com/sandykarunia/fudge/sdk"
)

// Injectors from file_wire.go:

func FileInstance() File {
	ioFunctions := sdk.ProvideIOFunctions()
	osFunctions := sdk.ProvideOSFunctions()
	utilsFile := ProvideFile(ioFunctions, osFunctions)
	return utilsFile
}

// Injectors from string_wire.go:

func StringInstance() String {
	utilsString := ProvideString()
	return utilsString
}

// Injectors from system_wire.go:

func SystemInstance() System {
	osFunctions := sdk.ProvideOSFunctions()
	utilsSystem := ProvideSystem(osFunctions)
	return utilsSystem
}
