// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package sdk

// Injectors from io_wire.go:

func IOInstance() IOFunctions {
	sdkIOFunctions := ProvideIOFunctions()
	return sdkIOFunctions
}

// Injectors from os_wire.go:

func OSInstance() OSFunctions {
	sdkOSFunctions := ProvideOSFunctions()
	return sdkOSFunctions
}
