// Code generated by mockery v1.0.0
package mocks

import (
	grader "github.com/sandykarunia/fudge/grader"
	mock "github.com/stretchr/testify/mock"
)

// Grader is an autogenerated mock type for the Grader type
type Grader struct {
	mock.Mock
}

// GradeAsync provides a mock function with given fields: payload
func (_m *Grader) GradeAsync(payload *grader.GradeAsyncPayload) bool {
	ret := _m.Called(payload)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*grader.GradeAsyncPayload) bool); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Status provides a mock function with given fields:
func (_m *Grader) Status() grader.Status {
	ret := _m.Called()

	var r0 grader.Status
	if rf, ok := ret.Get(0).(func() grader.Status); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(grader.Status)
	}

	return r0
}
