// Code generated by mockery v1.0.0
package mocks

import (
	grader "github.com/sandykarunia/fudge/grader"
	mock "github.com/stretchr/testify/mock"
)

// Grader is an autogenerated mock type for the Grader type
type Grader struct {
	mock.Mock
}

// Status provides a mock function with given fields:
func (_m *Grader) Status() grader.Status {
	ret := _m.Called()

	var r0 grader.Status
	if rf, ok := ret.Get(0).(func() grader.Status); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(grader.Status)
	}

	return r0
}
