// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Checkers is an autogenerated mock type for the Checkers type
type Checkers struct {
	mock.Mock
}

// CheckIsolateBinaryExecutable provides a mock function with given fields:
func (_m *Checkers) CheckIsolateBinaryExecutable() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CheckIsolateBinaryValid provides a mock function with given fields:
func (_m *Checkers) CheckIsolateBinaryValid() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CheckLibcapDevPkg provides a mock function with given fields:
func (_m *Checkers) CheckLibcapDevPkg() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CheckSudo provides a mock function with given fields:
func (_m *Checkers) CheckSudo() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
