// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// GroundCheck is an autogenerated mock type for the GroundCheck type
type GroundCheck struct {
	mock.Mock
}

// CheckAll provides a mock function with given fields:
func (_m *GroundCheck) CheckAll() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
