// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Debug provides a mock function with given fields: tag, message, args
func (_m *Logger) Debug(tag string, message string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, tag, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Error provides a mock function with given fields: tag, message, args
func (_m *Logger) Error(tag string, message string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, tag, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Fatal provides a mock function with given fields: tag, message, args
func (_m *Logger) Fatal(tag string, message string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, tag, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Info provides a mock function with given fields: tag, message, args
func (_m *Logger) Info(tag string, message string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, tag, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Security provides a mock function with given fields: tag, message, args
func (_m *Logger) Security(tag string, message string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, tag, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Warn provides a mock function with given fields: tag, message, args
func (_m *Logger) Warn(tag string, message string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, tag, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}
